#!/bin/bash
set -e
echo Extracting cards
python extract.py $1
if [ ! -f wishlist.csv ]; then
    exit 1
fi
echo "--------------------"
echo Starting scraping
python scrape.py wishlist.csv
echo "--------------------"
echo Starting summarizing
python summarize.py data_raw.csv
echo "--------------------"
echo Starting optimizing
python optimize.py data_processed.csv
